/*
Puupee API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package puupee

import (
	"encoding/json"
)

// checks if the CreateUpdateMessageSourceRouteDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUpdateMessageSourceRouteDto{}

// CreateUpdateMessageSourceRouteDto struct for CreateUpdateMessageSourceRouteDto
type CreateUpdateMessageSourceRouteDto struct {
	Title NullableString `json:"title,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Path NullableString `json:"path,omitempty"`
	SourceId *string `json:"sourceId,omitempty"`
	Extra NullableString `json:"extra,omitempty"`
	Anticrawler *bool `json:"anticrawler,omitempty"`
	Radar *bool `json:"radar,omitempty"`
	Rssbud *bool `json:"rssbud,omitempty"`
	IsPublished *bool `json:"isPublished,omitempty"`
	IconUrl NullableString `json:"iconUrl,omitempty"`
}

// NewCreateUpdateMessageSourceRouteDto instantiates a new CreateUpdateMessageSourceRouteDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUpdateMessageSourceRouteDto() *CreateUpdateMessageSourceRouteDto {
	this := CreateUpdateMessageSourceRouteDto{}
	return &this
}

// NewCreateUpdateMessageSourceRouteDtoWithDefaults instantiates a new CreateUpdateMessageSourceRouteDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUpdateMessageSourceRouteDtoWithDefaults() *CreateUpdateMessageSourceRouteDto {
	this := CreateUpdateMessageSourceRouteDto{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUpdateMessageSourceRouteDto) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateMessageSourceRouteDto) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *CreateUpdateMessageSourceRouteDto) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) UnsetTitle() {
	o.Title.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUpdateMessageSourceRouteDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateMessageSourceRouteDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateUpdateMessageSourceRouteDto) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) UnsetDescription() {
	o.Description.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUpdateMessageSourceRouteDto) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateMessageSourceRouteDto) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *CreateUpdateMessageSourceRouteDto) SetPath(v string) {
	o.Path.Set(&v)
}
// SetPathNil sets the value for Path to be an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) UnsetPath() {
	o.Path.Unset()
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *CreateUpdateMessageSourceRouteDto) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateMessageSourceRouteDto) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *CreateUpdateMessageSourceRouteDto) SetSourceId(v string) {
	o.SourceId = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUpdateMessageSourceRouteDto) GetExtra() string {
	if o == nil || IsNil(o.Extra.Get()) {
		var ret string
		return ret
	}
	return *o.Extra.Get()
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateMessageSourceRouteDto) GetExtraOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Extra.Get(), o.Extra.IsSet()
}

// HasExtra returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasExtra() bool {
	if o != nil && o.Extra.IsSet() {
		return true
	}

	return false
}

// SetExtra gets a reference to the given NullableString and assigns it to the Extra field.
func (o *CreateUpdateMessageSourceRouteDto) SetExtra(v string) {
	o.Extra.Set(&v)
}
// SetExtraNil sets the value for Extra to be an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) SetExtraNil() {
	o.Extra.Set(nil)
}

// UnsetExtra ensures that no value is present for Extra, not even an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) UnsetExtra() {
	o.Extra.Unset()
}

// GetAnticrawler returns the Anticrawler field value if set, zero value otherwise.
func (o *CreateUpdateMessageSourceRouteDto) GetAnticrawler() bool {
	if o == nil || IsNil(o.Anticrawler) {
		var ret bool
		return ret
	}
	return *o.Anticrawler
}

// GetAnticrawlerOk returns a tuple with the Anticrawler field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateMessageSourceRouteDto) GetAnticrawlerOk() (*bool, bool) {
	if o == nil || IsNil(o.Anticrawler) {
		return nil, false
	}
	return o.Anticrawler, true
}

// HasAnticrawler returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasAnticrawler() bool {
	if o != nil && !IsNil(o.Anticrawler) {
		return true
	}

	return false
}

// SetAnticrawler gets a reference to the given bool and assigns it to the Anticrawler field.
func (o *CreateUpdateMessageSourceRouteDto) SetAnticrawler(v bool) {
	o.Anticrawler = &v
}

// GetRadar returns the Radar field value if set, zero value otherwise.
func (o *CreateUpdateMessageSourceRouteDto) GetRadar() bool {
	if o == nil || IsNil(o.Radar) {
		var ret bool
		return ret
	}
	return *o.Radar
}

// GetRadarOk returns a tuple with the Radar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateMessageSourceRouteDto) GetRadarOk() (*bool, bool) {
	if o == nil || IsNil(o.Radar) {
		return nil, false
	}
	return o.Radar, true
}

// HasRadar returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasRadar() bool {
	if o != nil && !IsNil(o.Radar) {
		return true
	}

	return false
}

// SetRadar gets a reference to the given bool and assigns it to the Radar field.
func (o *CreateUpdateMessageSourceRouteDto) SetRadar(v bool) {
	o.Radar = &v
}

// GetRssbud returns the Rssbud field value if set, zero value otherwise.
func (o *CreateUpdateMessageSourceRouteDto) GetRssbud() bool {
	if o == nil || IsNil(o.Rssbud) {
		var ret bool
		return ret
	}
	return *o.Rssbud
}

// GetRssbudOk returns a tuple with the Rssbud field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateMessageSourceRouteDto) GetRssbudOk() (*bool, bool) {
	if o == nil || IsNil(o.Rssbud) {
		return nil, false
	}
	return o.Rssbud, true
}

// HasRssbud returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasRssbud() bool {
	if o != nil && !IsNil(o.Rssbud) {
		return true
	}

	return false
}

// SetRssbud gets a reference to the given bool and assigns it to the Rssbud field.
func (o *CreateUpdateMessageSourceRouteDto) SetRssbud(v bool) {
	o.Rssbud = &v
}

// GetIsPublished returns the IsPublished field value if set, zero value otherwise.
func (o *CreateUpdateMessageSourceRouteDto) GetIsPublished() bool {
	if o == nil || IsNil(o.IsPublished) {
		var ret bool
		return ret
	}
	return *o.IsPublished
}

// GetIsPublishedOk returns a tuple with the IsPublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateMessageSourceRouteDto) GetIsPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublished) {
		return nil, false
	}
	return o.IsPublished, true
}

// HasIsPublished returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasIsPublished() bool {
	if o != nil && !IsNil(o.IsPublished) {
		return true
	}

	return false
}

// SetIsPublished gets a reference to the given bool and assigns it to the IsPublished field.
func (o *CreateUpdateMessageSourceRouteDto) SetIsPublished(v bool) {
	o.IsPublished = &v
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUpdateMessageSourceRouteDto) GetIconUrl() string {
	if o == nil || IsNil(o.IconUrl.Get()) {
		var ret string
		return ret
	}
	return *o.IconUrl.Get()
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateMessageSourceRouteDto) GetIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IconUrl.Get(), o.IconUrl.IsSet()
}

// HasIconUrl returns a boolean if a field has been set.
func (o *CreateUpdateMessageSourceRouteDto) HasIconUrl() bool {
	if o != nil && o.IconUrl.IsSet() {
		return true
	}

	return false
}

// SetIconUrl gets a reference to the given NullableString and assigns it to the IconUrl field.
func (o *CreateUpdateMessageSourceRouteDto) SetIconUrl(v string) {
	o.IconUrl.Set(&v)
}
// SetIconUrlNil sets the value for IconUrl to be an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) SetIconUrlNil() {
	o.IconUrl.Set(nil)
}

// UnsetIconUrl ensures that no value is present for IconUrl, not even an explicit nil
func (o *CreateUpdateMessageSourceRouteDto) UnsetIconUrl() {
	o.IconUrl.Unset()
}

func (o CreateUpdateMessageSourceRouteDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUpdateMessageSourceRouteDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if !IsNil(o.SourceId) {
		toSerialize["sourceId"] = o.SourceId
	}
	if o.Extra.IsSet() {
		toSerialize["extra"] = o.Extra.Get()
	}
	if !IsNil(o.Anticrawler) {
		toSerialize["anticrawler"] = o.Anticrawler
	}
	if !IsNil(o.Radar) {
		toSerialize["radar"] = o.Radar
	}
	if !IsNil(o.Rssbud) {
		toSerialize["rssbud"] = o.Rssbud
	}
	if !IsNil(o.IsPublished) {
		toSerialize["isPublished"] = o.IsPublished
	}
	if o.IconUrl.IsSet() {
		toSerialize["iconUrl"] = o.IconUrl.Get()
	}
	return toSerialize, nil
}

type NullableCreateUpdateMessageSourceRouteDto struct {
	value *CreateUpdateMessageSourceRouteDto
	isSet bool
}

func (v NullableCreateUpdateMessageSourceRouteDto) Get() *CreateUpdateMessageSourceRouteDto {
	return v.value
}

func (v *NullableCreateUpdateMessageSourceRouteDto) Set(val *CreateUpdateMessageSourceRouteDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUpdateMessageSourceRouteDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUpdateMessageSourceRouteDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUpdateMessageSourceRouteDto(val *CreateUpdateMessageSourceRouteDto) *NullableCreateUpdateMessageSourceRouteDto {
	return &NullableCreateUpdateMessageSourceRouteDto{value: val, isSet: true}
}

func (v NullableCreateUpdateMessageSourceRouteDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUpdateMessageSourceRouteDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


