/*
Puupee API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.17.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package puupee

import (
	"encoding/json"
)

// checks if the ApplicationLocalizationConfigurationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationLocalizationConfigurationDto{}

// ApplicationLocalizationConfigurationDto struct for ApplicationLocalizationConfigurationDto
type ApplicationLocalizationConfigurationDto struct {
	Values *map[string]map[string]string `json:"values,omitempty"`
	Resources *map[string]ApplicationLocalizationResourceDto `json:"resources,omitempty"`
	Languages []LanguageInfo `json:"languages,omitempty"`
	CurrentCulture *CurrentCultureDto `json:"currentCulture,omitempty"`
	DefaultResourceName *string `json:"defaultResourceName,omitempty"`
	LanguagesMap *map[string][]NameValue `json:"languagesMap,omitempty"`
	LanguageFilesMap *map[string][]NameValue `json:"languageFilesMap,omitempty"`
}

// NewApplicationLocalizationConfigurationDto instantiates a new ApplicationLocalizationConfigurationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationLocalizationConfigurationDto() *ApplicationLocalizationConfigurationDto {
	this := ApplicationLocalizationConfigurationDto{}
	return &this
}

// NewApplicationLocalizationConfigurationDtoWithDefaults instantiates a new ApplicationLocalizationConfigurationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationLocalizationConfigurationDtoWithDefaults() *ApplicationLocalizationConfigurationDto {
	this := ApplicationLocalizationConfigurationDto{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetValues() map[string]map[string]string {
	if o == nil || IsNil(o.Values) {
		var ret map[string]map[string]string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetValuesOk() (*map[string]map[string]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]map[string]string and assigns it to the Values field.
func (o *ApplicationLocalizationConfigurationDto) SetValues(v map[string]map[string]string) {
	o.Values = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetResources() map[string]ApplicationLocalizationResourceDto {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]ApplicationLocalizationResourceDto
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetResourcesOk() (*map[string]ApplicationLocalizationResourceDto, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]ApplicationLocalizationResourceDto and assigns it to the Resources field.
func (o *ApplicationLocalizationConfigurationDto) SetResources(v map[string]ApplicationLocalizationResourceDto) {
	o.Resources = &v
}

// GetLanguages returns the Languages field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetLanguages() []LanguageInfo {
	if o == nil || IsNil(o.Languages) {
		var ret []LanguageInfo
		return ret
	}
	return o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetLanguagesOk() ([]LanguageInfo, bool) {
	if o == nil || IsNil(o.Languages) {
		return nil, false
	}
	return o.Languages, true
}

// HasLanguages returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasLanguages() bool {
	if o != nil && !IsNil(o.Languages) {
		return true
	}

	return false
}

// SetLanguages gets a reference to the given []LanguageInfo and assigns it to the Languages field.
func (o *ApplicationLocalizationConfigurationDto) SetLanguages(v []LanguageInfo) {
	o.Languages = v
}

// GetCurrentCulture returns the CurrentCulture field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetCurrentCulture() CurrentCultureDto {
	if o == nil || IsNil(o.CurrentCulture) {
		var ret CurrentCultureDto
		return ret
	}
	return *o.CurrentCulture
}

// GetCurrentCultureOk returns a tuple with the CurrentCulture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetCurrentCultureOk() (*CurrentCultureDto, bool) {
	if o == nil || IsNil(o.CurrentCulture) {
		return nil, false
	}
	return o.CurrentCulture, true
}

// HasCurrentCulture returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasCurrentCulture() bool {
	if o != nil && !IsNil(o.CurrentCulture) {
		return true
	}

	return false
}

// SetCurrentCulture gets a reference to the given CurrentCultureDto and assigns it to the CurrentCulture field.
func (o *ApplicationLocalizationConfigurationDto) SetCurrentCulture(v CurrentCultureDto) {
	o.CurrentCulture = &v
}

// GetDefaultResourceName returns the DefaultResourceName field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetDefaultResourceName() string {
	if o == nil || IsNil(o.DefaultResourceName) {
		var ret string
		return ret
	}
	return *o.DefaultResourceName
}

// GetDefaultResourceNameOk returns a tuple with the DefaultResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetDefaultResourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultResourceName) {
		return nil, false
	}
	return o.DefaultResourceName, true
}

// HasDefaultResourceName returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasDefaultResourceName() bool {
	if o != nil && !IsNil(o.DefaultResourceName) {
		return true
	}

	return false
}

// SetDefaultResourceName gets a reference to the given string and assigns it to the DefaultResourceName field.
func (o *ApplicationLocalizationConfigurationDto) SetDefaultResourceName(v string) {
	o.DefaultResourceName = &v
}

// GetLanguagesMap returns the LanguagesMap field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetLanguagesMap() map[string][]NameValue {
	if o == nil || IsNil(o.LanguagesMap) {
		var ret map[string][]NameValue
		return ret
	}
	return *o.LanguagesMap
}

// GetLanguagesMapOk returns a tuple with the LanguagesMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetLanguagesMapOk() (*map[string][]NameValue, bool) {
	if o == nil || IsNil(o.LanguagesMap) {
		return nil, false
	}
	return o.LanguagesMap, true
}

// HasLanguagesMap returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasLanguagesMap() bool {
	if o != nil && !IsNil(o.LanguagesMap) {
		return true
	}

	return false
}

// SetLanguagesMap gets a reference to the given map[string][]NameValue and assigns it to the LanguagesMap field.
func (o *ApplicationLocalizationConfigurationDto) SetLanguagesMap(v map[string][]NameValue) {
	o.LanguagesMap = &v
}

// GetLanguageFilesMap returns the LanguageFilesMap field value if set, zero value otherwise.
func (o *ApplicationLocalizationConfigurationDto) GetLanguageFilesMap() map[string][]NameValue {
	if o == nil || IsNil(o.LanguageFilesMap) {
		var ret map[string][]NameValue
		return ret
	}
	return *o.LanguageFilesMap
}

// GetLanguageFilesMapOk returns a tuple with the LanguageFilesMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationLocalizationConfigurationDto) GetLanguageFilesMapOk() (*map[string][]NameValue, bool) {
	if o == nil || IsNil(o.LanguageFilesMap) {
		return nil, false
	}
	return o.LanguageFilesMap, true
}

// HasLanguageFilesMap returns a boolean if a field has been set.
func (o *ApplicationLocalizationConfigurationDto) HasLanguageFilesMap() bool {
	if o != nil && !IsNil(o.LanguageFilesMap) {
		return true
	}

	return false
}

// SetLanguageFilesMap gets a reference to the given map[string][]NameValue and assigns it to the LanguageFilesMap field.
func (o *ApplicationLocalizationConfigurationDto) SetLanguageFilesMap(v map[string][]NameValue) {
	o.LanguageFilesMap = &v
}

func (o ApplicationLocalizationConfigurationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationLocalizationConfigurationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Languages) {
		toSerialize["languages"] = o.Languages
	}
	if !IsNil(o.CurrentCulture) {
		toSerialize["currentCulture"] = o.CurrentCulture
	}
	if !IsNil(o.DefaultResourceName) {
		toSerialize["defaultResourceName"] = o.DefaultResourceName
	}
	if !IsNil(o.LanguagesMap) {
		toSerialize["languagesMap"] = o.LanguagesMap
	}
	if !IsNil(o.LanguageFilesMap) {
		toSerialize["languageFilesMap"] = o.LanguageFilesMap
	}
	return toSerialize, nil
}

type NullableApplicationLocalizationConfigurationDto struct {
	value *ApplicationLocalizationConfigurationDto
	isSet bool
}

func (v NullableApplicationLocalizationConfigurationDto) Get() *ApplicationLocalizationConfigurationDto {
	return v.value
}

func (v *NullableApplicationLocalizationConfigurationDto) Set(val *ApplicationLocalizationConfigurationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationLocalizationConfigurationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationLocalizationConfigurationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationLocalizationConfigurationDto(val *ApplicationLocalizationConfigurationDto) *NullableApplicationLocalizationConfigurationDto {
	return &NullableApplicationLocalizationConfigurationDto{value: val, isSet: true}
}

func (v NullableApplicationLocalizationConfigurationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationLocalizationConfigurationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


