/*
Puupee API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package puupee

import (
	"encoding/json"
)

// MessageTemplateDto struct for MessageTemplateDto
type MessageTemplateDto struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	LatestVersion *int32 `json:"latestVersion,omitempty"`
}

// NewMessageTemplateDto instantiates a new MessageTemplateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageTemplateDto() *MessageTemplateDto {
	this := MessageTemplateDto{}
	return &this
}

// NewMessageTemplateDtoWithDefaults instantiates a new MessageTemplateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageTemplateDtoWithDefaults() *MessageTemplateDto {
	this := MessageTemplateDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MessageTemplateDto) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageTemplateDto) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MessageTemplateDto) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MessageTemplateDto) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MessageTemplateDto) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageTemplateDto) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MessageTemplateDto) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MessageTemplateDto) SetDescription(v string) {
	o.Description = &v
}

// GetLatestVersion returns the LatestVersion field value if set, zero value otherwise.
func (o *MessageTemplateDto) GetLatestVersion() int32 {
	if o == nil || isNil(o.LatestVersion) {
		var ret int32
		return ret
	}
	return *o.LatestVersion
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageTemplateDto) GetLatestVersionOk() (*int32, bool) {
	if o == nil || isNil(o.LatestVersion) {
    return nil, false
	}
	return o.LatestVersion, true
}

// HasLatestVersion returns a boolean if a field has been set.
func (o *MessageTemplateDto) HasLatestVersion() bool {
	if o != nil && !isNil(o.LatestVersion) {
		return true
	}

	return false
}

// SetLatestVersion gets a reference to the given int32 and assigns it to the LatestVersion field.
func (o *MessageTemplateDto) SetLatestVersion(v int32) {
	o.LatestVersion = &v
}

func (o MessageTemplateDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.LatestVersion) {
		toSerialize["latestVersion"] = o.LatestVersion
	}
	return json.Marshal(toSerialize)
}

type NullableMessageTemplateDto struct {
	value *MessageTemplateDto
	isSet bool
}

func (v NullableMessageTemplateDto) Get() *MessageTemplateDto {
	return v.value
}

func (v *NullableMessageTemplateDto) Set(val *MessageTemplateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageTemplateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageTemplateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageTemplateDto(val *MessageTemplateDto) *NullableMessageTemplateDto {
	return &NullableMessageTemplateDto{value: val, isSet: true}
}

func (v NullableMessageTemplateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageTemplateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


