/*
Puupee API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package puupee

import (
	"encoding/json"
)

// checks if the ControllerInterfaceApiDescriptionModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllerInterfaceApiDescriptionModel{}

// ControllerInterfaceApiDescriptionModel struct for ControllerInterfaceApiDescriptionModel
type ControllerInterfaceApiDescriptionModel struct {
	Type *string `json:"type,omitempty"`
	Name *string `json:"name,omitempty"`
	Methods []InterfaceMethodApiDescriptionModel `json:"methods,omitempty"`
}

// NewControllerInterfaceApiDescriptionModel instantiates a new ControllerInterfaceApiDescriptionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllerInterfaceApiDescriptionModel() *ControllerInterfaceApiDescriptionModel {
	this := ControllerInterfaceApiDescriptionModel{}
	return &this
}

// NewControllerInterfaceApiDescriptionModelWithDefaults instantiates a new ControllerInterfaceApiDescriptionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllerInterfaceApiDescriptionModelWithDefaults() *ControllerInterfaceApiDescriptionModel {
	this := ControllerInterfaceApiDescriptionModel{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ControllerInterfaceApiDescriptionModel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerInterfaceApiDescriptionModel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ControllerInterfaceApiDescriptionModel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ControllerInterfaceApiDescriptionModel) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ControllerInterfaceApiDescriptionModel) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerInterfaceApiDescriptionModel) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ControllerInterfaceApiDescriptionModel) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ControllerInterfaceApiDescriptionModel) SetName(v string) {
	o.Name = &v
}

// GetMethods returns the Methods field value if set, zero value otherwise.
func (o *ControllerInterfaceApiDescriptionModel) GetMethods() []InterfaceMethodApiDescriptionModel {
	if o == nil || IsNil(o.Methods) {
		var ret []InterfaceMethodApiDescriptionModel
		return ret
	}
	return o.Methods
}

// GetMethodsOk returns a tuple with the Methods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllerInterfaceApiDescriptionModel) GetMethodsOk() ([]InterfaceMethodApiDescriptionModel, bool) {
	if o == nil || IsNil(o.Methods) {
		return nil, false
	}
	return o.Methods, true
}

// HasMethods returns a boolean if a field has been set.
func (o *ControllerInterfaceApiDescriptionModel) HasMethods() bool {
	if o != nil && !IsNil(o.Methods) {
		return true
	}

	return false
}

// SetMethods gets a reference to the given []InterfaceMethodApiDescriptionModel and assigns it to the Methods field.
func (o *ControllerInterfaceApiDescriptionModel) SetMethods(v []InterfaceMethodApiDescriptionModel) {
	o.Methods = v
}

func (o ControllerInterfaceApiDescriptionModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllerInterfaceApiDescriptionModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Methods) {
		toSerialize["methods"] = o.Methods
	}
	return toSerialize, nil
}

type NullableControllerInterfaceApiDescriptionModel struct {
	value *ControllerInterfaceApiDescriptionModel
	isSet bool
}

func (v NullableControllerInterfaceApiDescriptionModel) Get() *ControllerInterfaceApiDescriptionModel {
	return v.value
}

func (v *NullableControllerInterfaceApiDescriptionModel) Set(val *ControllerInterfaceApiDescriptionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableControllerInterfaceApiDescriptionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableControllerInterfaceApiDescriptionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllerInterfaceApiDescriptionModel(val *ControllerInterfaceApiDescriptionModel) *NullableControllerInterfaceApiDescriptionModel {
	return &NullableControllerInterfaceApiDescriptionModel{value: val, isSet: true}
}

func (v NullableControllerInterfaceApiDescriptionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllerInterfaceApiDescriptionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


