/*
Doggy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doggy

import (
	"encoding/json"
)

// AppType struct for AppType
type AppType struct {
}

// NewAppType instantiates a new AppType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppType() *AppType {
	this := AppType{}
	return &this
}

// NewAppTypeWithDefaults instantiates a new AppType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppTypeWithDefaults() *AppType {
	this := AppType{}
	return &this
}

func (o AppType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableAppType struct {
	value *AppType
	isSet bool
}

func (v NullableAppType) Get() *AppType {
	return v.value
}

func (v *NullableAppType) Set(val *AppType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppType(val *AppType) *NullableAppType {
	return &NullableAppType{value: val, isSet: true}
}

func (v NullableAppType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


