/*
Doggy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doggy

import (
	"encoding/json"
)

// ItemType struct for ItemType
type ItemType struct {
}

// NewItemType instantiates a new ItemType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemType() *ItemType {
	this := ItemType{}
	return &this
}

// NewItemTypeWithDefaults instantiates a new ItemType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemTypeWithDefaults() *ItemType {
	this := ItemType{}
	return &this
}

func (o ItemType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableItemType struct {
	value *ItemType
	isSet bool
}

func (v NullableItemType) Get() *ItemType {
	return v.value
}

func (v *NullableItemType) Set(val *ItemType) {
	v.value = val
	v.isSet = true
}

func (v NullableItemType) IsSet() bool {
	return v.isSet
}

func (v *NullableItemType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemType(val *ItemType) *NullableItemType {
	return &NullableItemType{value: val, isSet: true}
}

func (v NullableItemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


