/*
Doggy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package doggy

import (
	"encoding/json"
)

// PermissionGrantInfoDto struct for PermissionGrantInfoDto
type PermissionGrantInfoDto struct {
	Name NullableString `json:"name,omitempty"`
	DisplayName NullableString `json:"displayName,omitempty"`
	ParentName NullableString `json:"parentName,omitempty"`
	IsGranted *bool `json:"isGranted,omitempty"`
	AllowedProviders []string `json:"allowedProviders,omitempty"`
	GrantedProviders []ProviderInfoDto `json:"grantedProviders,omitempty"`
}

// NewPermissionGrantInfoDto instantiates a new PermissionGrantInfoDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGrantInfoDto() *PermissionGrantInfoDto {
	this := PermissionGrantInfoDto{}
	return &this
}

// NewPermissionGrantInfoDtoWithDefaults instantiates a new PermissionGrantInfoDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGrantInfoDtoWithDefaults() *PermissionGrantInfoDto {
	this := PermissionGrantInfoDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PermissionGrantInfoDto) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PermissionGrantInfoDto) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PermissionGrantInfoDto) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *PermissionGrantInfoDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PermissionGrantInfoDto) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PermissionGrantInfoDto) GetDisplayName() string {
	if o == nil || o.DisplayName.Get() == nil {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PermissionGrantInfoDto) GetDisplayNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *PermissionGrantInfoDto) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *PermissionGrantInfoDto) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *PermissionGrantInfoDto) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetParentName returns the ParentName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PermissionGrantInfoDto) GetParentName() string {
	if o == nil || o.ParentName.Get() == nil {
		var ret string
		return ret
	}
	return *o.ParentName.Get()
}

// GetParentNameOk returns a tuple with the ParentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PermissionGrantInfoDto) GetParentNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ParentName.Get(), o.ParentName.IsSet()
}

// HasParentName returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasParentName() bool {
	if o != nil && o.ParentName.IsSet() {
		return true
	}

	return false
}

// SetParentName gets a reference to the given NullableString and assigns it to the ParentName field.
func (o *PermissionGrantInfoDto) SetParentName(v string) {
	o.ParentName.Set(&v)
}
// SetParentNameNil sets the value for ParentName to be an explicit nil
func (o *PermissionGrantInfoDto) SetParentNameNil() {
	o.ParentName.Set(nil)
}

// UnsetParentName ensures that no value is present for ParentName, not even an explicit nil
func (o *PermissionGrantInfoDto) UnsetParentName() {
	o.ParentName.Unset()
}

// GetIsGranted returns the IsGranted field value if set, zero value otherwise.
func (o *PermissionGrantInfoDto) GetIsGranted() bool {
	if o == nil || o.IsGranted == nil {
		var ret bool
		return ret
	}
	return *o.IsGranted
}

// GetIsGrantedOk returns a tuple with the IsGranted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGrantInfoDto) GetIsGrantedOk() (*bool, bool) {
	if o == nil || o.IsGranted == nil {
		return nil, false
	}
	return o.IsGranted, true
}

// HasIsGranted returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasIsGranted() bool {
	if o != nil && o.IsGranted != nil {
		return true
	}

	return false
}

// SetIsGranted gets a reference to the given bool and assigns it to the IsGranted field.
func (o *PermissionGrantInfoDto) SetIsGranted(v bool) {
	o.IsGranted = &v
}

// GetAllowedProviders returns the AllowedProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PermissionGrantInfoDto) GetAllowedProviders() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.AllowedProviders
}

// GetAllowedProvidersOk returns a tuple with the AllowedProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PermissionGrantInfoDto) GetAllowedProvidersOk() (*[]string, bool) {
	if o == nil || o.AllowedProviders == nil {
		return nil, false
	}
	return &o.AllowedProviders, true
}

// HasAllowedProviders returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasAllowedProviders() bool {
	if o != nil && o.AllowedProviders != nil {
		return true
	}

	return false
}

// SetAllowedProviders gets a reference to the given []string and assigns it to the AllowedProviders field.
func (o *PermissionGrantInfoDto) SetAllowedProviders(v []string) {
	o.AllowedProviders = v
}

// GetGrantedProviders returns the GrantedProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PermissionGrantInfoDto) GetGrantedProviders() []ProviderInfoDto {
	if o == nil  {
		var ret []ProviderInfoDto
		return ret
	}
	return o.GrantedProviders
}

// GetGrantedProvidersOk returns a tuple with the GrantedProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PermissionGrantInfoDto) GetGrantedProvidersOk() (*[]ProviderInfoDto, bool) {
	if o == nil || o.GrantedProviders == nil {
		return nil, false
	}
	return &o.GrantedProviders, true
}

// HasGrantedProviders returns a boolean if a field has been set.
func (o *PermissionGrantInfoDto) HasGrantedProviders() bool {
	if o != nil && o.GrantedProviders != nil {
		return true
	}

	return false
}

// SetGrantedProviders gets a reference to the given []ProviderInfoDto and assigns it to the GrantedProviders field.
func (o *PermissionGrantInfoDto) SetGrantedProviders(v []ProviderInfoDto) {
	o.GrantedProviders = v
}

func (o PermissionGrantInfoDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.ParentName.IsSet() {
		toSerialize["parentName"] = o.ParentName.Get()
	}
	if o.IsGranted != nil {
		toSerialize["isGranted"] = o.IsGranted
	}
	if o.AllowedProviders != nil {
		toSerialize["allowedProviders"] = o.AllowedProviders
	}
	if o.GrantedProviders != nil {
		toSerialize["grantedProviders"] = o.GrantedProviders
	}
	return json.Marshal(toSerialize)
}

type NullablePermissionGrantInfoDto struct {
	value *PermissionGrantInfoDto
	isSet bool
}

func (v NullablePermissionGrantInfoDto) Get() *PermissionGrantInfoDto {
	return v.value
}

func (v *NullablePermissionGrantInfoDto) Set(val *PermissionGrantInfoDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGrantInfoDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGrantInfoDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGrantInfoDto(val *PermissionGrantInfoDto) *NullablePermissionGrantInfoDto {
	return &NullablePermissionGrantInfoDto{value: val, isSet: true}
}

func (v NullablePermissionGrantInfoDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGrantInfoDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


